version: 1.{build}
image: Visual Studio 2019 Preview
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/FramerateVigilante.sln
  verbosity: minimal
artifacts:
- path: bin\FramerateVigilante\scripts\*.asi